# .streamlit/secrets.toml

[mysql]
host = "localhost"
port = 3306
database = "database_name" # Database name
user = "xxxx" # Server User. Can be found on MySQL Workbench > Administration tab > Users and Privileges > User Accounts (first user)
password = "xxxx" # Server Password
